### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by hfiguiere**
- also I did reorg the manifest to put things in a more natural order.

### CODE REVIEW

**Comment by hfiguiere** [comment]
build was fine locally.

**Comment by hfiguiere** [comment]
This should be good now. I upgraded gtk2hs-buildtools as the version built failed to parse the headers in the SDK.

My build works locally.

**Comment by wjt** [comment]
You are braver than me!

**Comment by wjt** [comment]
The manifest had stuff in a weird order because it was (partly) mechanically generated as described in d6b7d7d1882265a13acf9a32ecc0b8f1d93cd961

**Review by wjt — APPROVED** [review]
LGTM, I'll await a test build.

**Comment by hfiguiere** [comment]
need to figure out the aarch64 failure

**Comment by hfiguiere** [comment]
no idea why it's failing on aarch64.

**Comment by wjt** [comment]
bot, build

**Comment by hfiguiere** [comment]
I gave up and my aarch64 system who run out of disk space building this is currently off. (I know nothing about the obscure language/runtime used here)

**Comment by hfiguiere** [comment]
Since the runtime is now EOL I decided to try with at least 21.08... That leave one more year to figure it out.

**Comment by hfiguiere** [comment]
bot, build

**Comment by A6GibKm** [comment]
~~Time for 22.08~~

**Comment by hfiguiere** [comment]
let's see if adding llvm14 fixes it.

**Comment by hfiguiere** [comment]
WFM on x86_64. I can't test aarch64 at the moment though, but it did build.

**Pull request merged**
